### ISSUE TITLE
TravisCIを導入する

### ISSUE THREAD

**Issue by lyuich** [lyuich/brain#112]
### Write a summary of this issue
- TravisCIを導入する

### List the details of what to do as a list
- [ ] .travis.ymlの基本
- [ ] Slack連携させる

### Any references (Describe URL of documents or webpages)
- なし

**Comment by lyuich** [comment]
## 1. TravisCIの基本
- Rubyの場合
```
sudo: false
language: ruby
rvm:
  - 2.0.0
before_install: gem install bundler -v 1.12.5
```
## 2. TravisCIとSlackを連携させる
```
$ gem install travis

$ travis login --pro

$ travis encrypt "<account>:<token>" --add notifications.slack
```

- `.travis.yml` に以下が追加される

```
notifications:
  email: false
  slack:
    secure: XXXXXXXXXX
```
