### ISSUE TITLE
Ansible Playbookの概要と構造を理解し、実行できるようにする

### ISSUE THREAD

**Issue by lyuich** [lyuich/brain#48]
### Write a summary of this issue
- Ansible Playbookの構造を理解して、実行できるようにする

### List the details of what to do as a list
- [ ] Playbookの概要が分かるようにする
- [ ] Playbookの構造を理解できるようにする
- [ ] Playbookの実行方法を記載する

### Any references (Describe URL of documents or webpages)
- なし

**Comment by lyuich** [comment]
# Ansible Playbookで対象ホストで実行するタスクを記述する

## 1. Playbookとは
- Ansibleで対象ホストに対するタスクを記述するYAMLファイル
- 複数のモジュールをまとめて実行する際にこのPlaybookに記述する

### シンプルなPlaybookのサンプル
- Apacheをyumでインストールし、httpdサービスの起動とOS起動時の自動起動の設定を行っている

```
---
- hosts: vm1
  become: true
  tasks: 
  - name: Apacheをインストール
    yum: name=httpd state=latest
  - name: Apacheを起動する
    service: name=httpd state=started enabled=yes
```

### Playbookの実行
- Playbookを実行するには、ansible-playbookコマンドを利用する

```
$ ansible-playbook -i hosts1-3 list2-1.yml

PLAY [vm1] ******************************

GATHERING FACTS *************************
ok: [vm1]

TASK: [Apacheをインストール] ************
changed: [vm1]

TASK: [Apacheを起動する] ****************
changed: [vm1]

PLAY RECAP ******************************
vm1       : ok=3 changed=2 unreachable=0
failed=0
```

## 2. Playbookの構造
- 1つのディクショナリには、対象ホストと実行タスクのリストが記述される
- このディクショナリを、playと呼ぶ
```
---
- hosts: web
  tasks:
    - name: install httpd
      yum: name=httpd state=latest

    - name: start and enable httpd
      service: name=httpd state=started enabled=yes

- hosts: db
  tasks:
    - name: install PostgreSQL Server
      yum: name=postgresql-server state=latest
```

### playで設定する主なキー
- `hosts`: 対象ホストパターン (必須)
- `tasks`: 実行タスクのリスト (必須)
- `vars`: playで有効な変数を設定
- `vars_files`: 変数が設定されたYAMLファイルを取り込む
- `remote_user`: 対象ホストへ接続するユーザ
- `become`: trueの場合に `remote_user` と異なるユーザでタスクを実行
- ` become_method`: becomeがtrueの場合に指定された方法でユーザを変更する
- ` became_user`: タスクを実行するユーザ
- `sudo`: trueの場合にタスクをsudoで実行する (非推奨)
- `handlers`: タスクの実行で変更があった場合に実行されるハンドラ
- `include`: 指定されたYAMLファイルをplayとして読み込む

### hosts
- タスクを実行するホストを指定
- インベントリに含まれているホストが対象
- ansibleコマンドでしてしたようにグループやパターンで複数のホストを指定可能

### tasks
- 実行するタスクをリストで指定する
- リストを構成する各タスクはディクショナリで記述する
- 各タスクでは以下のようなキーが指定できる

#### タスクで指定する主なキー
- `name`: タスクの実行内容を記述
- `MODULE_NAME`: 実行するモジュールを指定する
- `action`: 事項するモジュールを指定
- `local_action`: 対象ホストではなく、実行ホストで実行するモジュールを指定
- `when`: タスクを実行する条件を指定
- `register`: 値に指定された文字列を変数として、タスクの実行結果に格納
- `ignore_errors`: trueの場合にタスクがエラーになっても以降のタスクを実行
- `become`: trueの場合に `remote_user` と異なるユーザでタスクを実行
- `become_method`: becomeがtrueの場合に指定された方法でユーザを変更
- `become_user`: タスクを実行するユーザ名
- `notify`: モジュールの実行結果がchangedであれば、指定されたハンドラを実行
- `tags`: タスクにタグを設定する
- `include`: 指定されたYAMLファイルをタスクとして読み込む

### handlers
- タスク実行後に実行するハンドラを指定
- `notify` に実行するハンドラの `name` を指定する
- ex. httpdの設定ファイルを変更した後に設定を反映させるためにhttpdを再起動する、など

```
tasks:
  - name: 設定ファイルを転送
    copy: src=files/httpd.conf dest=/etc/httpd/conf/httpd.conf
    notify: httpdを再起動

handler:
  - name: httpdを再起動
    service: name=httpd state=restarted
```
