### ISSUE TITLE
AnsibleでLAPP (Linux+Apache+PHP+PostgresSQL) 構成のサーバを構築出来るようにする

### ISSUE THREAD

**Issue by lyuich** [lyuich/brain#52]
### Write a summary of this issue
- AnsibleでLAPPサーバ構築ができるようにする

### List the details of what to do as a list
- [ ] 仮想サーバの構築方法
- [ ] インベントリのサンプルを用意
- [ ] 基本的なセットアップをPlaybookに記述
- [ ] Apache, PHP, PostgreSQLのセットアップをPlaybookに記述

### Any references (Describe URL of documents or webpages)
- なし

**Comment by lyuich** [comment]
# AnsibleでLAPPサーバの構築
- Vagrant + VirtualBoxで仮想サーバを構築
- その上にLAPP (Linux+Apache+PHP+PostgreSQL)構成のサーバを構築
- WebアプリケーションはLaravelで実装

## 構築するサーバの構成
```
- CentOS 7
- Apache 2.4
- PHP 7.0
- PostgreSQL 9.4
```

## 仮想サーバの構築
- Vagrantで仮想サーバを構築するためにVagrantfileを用意

```
# -*- mode: ruby-*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |provider, override|
    provider.name = `servergroup-devops-ansible3"
    provider.memory = 1024
  end

  config.vm.box = 'bento/cetos-7.1'
  config.vm.hostname = 'servergroup-devops-ansible3.dev'
  config.vm.network :private_network, ip: '192.168.34.23'

  config.vm.synced_folder '.', '/vagrant', mount_options: ['dmode=777', 'fmode=666']
end
```

### ファイル構成
- filesディレクトリにはtemplate, copyモジュールで転送する設定ファイルを格納
- インベントリはhosts, Playbookはlapp.yml
- srcディレクトリにはWebアプリケーションをデプロイする

```
├── Vagrantfile
├── files
│   ├── apache
│   │   ├── httpd.conf.j2
│   │   └── vhosts.conf.js
│   ├── deploy
│   ├── php
│   │   └── zzmyphp.ini
│   └── postgresql
│       └── pg_hba.conf.j2
├── hosts
├── lapp.yml
└── src
```

## インベントリ
- 仮想サーバは1台で構築するのでホストは `vagrant_vm1` のみ
- このホストをvagrantグループに配置してVagrant関連の変数を定義
- `is_development` はPlaybookやテンプレートファイルでの判定に利用
- その他の変数はミドルウェアのインストールやアプリケーションのデプロイに利用

```
[vagrant]
vagrant_vm1 ansible_ssh_host=192.168.34.23

[vagrant:vars]
ansible_ssh_user=vagrant
ansible_ssh_private_key_file=~/.vagrant.d/insecure_private_key
is_development=True

# for apache
apache_document_root=/vagrant/src/public
apache_server_name=servergroup-devops-ansible3.dev

# for laravel and apache
deploy_laravel_root=/vagrant/src
deploy_laravel_env=local
deploy_laravel_debug=True
deploy_laravel_app_key=xxxxxxx # 要変更

# for laravel and postgresql
db_connction=pgsql
db_host="null"
db_database=app
db_test_database=app_test
db_username=vagrant
db_password=pass
```

## Playbook
- まず基本的なセットアップを行なう
  - ロケール, タイムゾーンの設定
  - 必要最低限のパッケージのインストール, ntpdの起動など
- 後で、このPlaybookにタスクを追加していく

```
---
- hosts: all
  become: yes
  vars:
    base_locale: LANG=ja_JP.UTF-8
    base_timezone: Asia/Tokyo
  tasks:
    - name: ロケール設定
      command: localectl set-locale {{ base_locale }}

    - name: タイムゾーン設定
      command: timedatectl set-timezone {{ base_timezone }}

    - name: 基本パッケージをインストール
      yum: name= {{ item }} state=present
      with_items:
        - vim
        - git
        - ntp

    - name: ntpdを起動、自動起動の有効化
      service: name=ntpd state=started enabled=yes
```

### Apacheのセットアップ
- Apacheのセットアップを行なうタスクを追加
- apacheタグを付与し、ansible-playbookの `-t` で指定出来るようにする

```
- name: Apacheをインストール
  yum: name=httpd state=present
  tags:
    - apache

- name: httpd.confテンプレートを転送
  template
    src=file/apache/httpd.conf.j2
    dest=/etc/httpd/conf/httpd.conf
    owner=root
    group=root
    mode=0644
  tags:
    - apache
  notify:
    - Apacheを再起動

- name: vhosts.confテンプレートを送信
  template:
    src=files/apache/vhosts.conf.j2
    dest=/etc/httpd/conf.d/vhosts.conf
    owner=root
    group=root
    mode=0644
  tags:
    - apache
  notify:
    - Apacheを再起動

- name: Apacheを起動、自動起動を有効化
  service: name=httpd state=started enabled=yes
  tags:
    - apache
```

#### httpd.conf.j2の可変部分
- httpdパッケージに含まれるhttpd.confをコピーしたもの
- `is_development` がtrueなら `EnableMMAP` と `EnableSendfile` をOffにする

```
{% if is_development %}
EnableMMAP Off
EnableSendfile Off
{% else %}
EnableMMAP On
EnableSendfile On
{% endif %}
```

#### Apacheを再起動するハンドラ
```
handlers:
  - name: Apacheを再起動
    service: name=httpd state=restarted
```

### PHPのセットアップ
1. RemiリポジトリにはEPELリポジトリが必要なのでyumでインストール 
2. Remiリポジトリがインストール済みかrpmコマンドで確認
3. (2)が `failed` ならRemiリポジトリをyumでインストール
4. yumモジュールでPHPと拡張パッケージをインストール
5. PHPの設定ファイルを転送
6. shellモジュールでComposerのインストールを実行

```
- name: EPELリポジトリをインストール
  yum: name=epel-release state=present
  tags:
    - php

- name: Remiリポジトリがインストール済みか
  shell: rpm -q remi-release
  register: remi_release_status
  faile_when: False
  changed_when: False
  tags:
    - php

- name: Remiリポジトリをインストール
  yum: name="http://rpms.remirepo.net/enterprise/remi-release-7.rpm"
  when: remi_release_status|failed
  tags:
    - php

- name: PHP 7.0をインストール
  yum: name={{ item }} state=present enablerepo=remi-php70
  with_items:
    - php
    - php-cli
    - php-process
    - php-pdo
    - php-pgsql
    - php-mbstring
    - php-mcrypt
    - php-devel
    - php-common
    - php-pear
    - php-opcache
    - php-json
    - php-pecl-memcached
    - php-pecl-zip
  notify:
    - Apacheを再起動
  tags:
    php

- name: カスタムphp.iniを転送
  copy: src=files/php/zzmyphp.ini dest=/etc/php.d/zzmyphp.ini
  notify: 
    - Apacheを再起動
  tags:
    - php

- name: composer.pharインストール
  shell: curl -sS https://getcomposer.org/installer
    | php -- --install-dir=/usr/bin --filename=composer creates=/usr/bin/composer
  tags:
    - php
```

### PostgreSQLのセットアップ
1. PostgreSQLがインストール済みかを確認
2. インストールされていなければ、PostgreSQLをインストール
3. PostgreSQLのパッケージをインストール
4. データベースクラスタの初期化を行なう
5. PostgreSQLでアクセス制御を行なうテンプレートを転送
6. Postgresの起動と自動起動の有効化
7. データベースユーザを作成
8. (7)のデータベースユーザをオーナーとしてデータベースを作成

```
- name: PostgreSQLリポジトリがインストール済みか
  shell: rpm -q pgdg-centos94
  register: pgdg_status
  failed_when: False
  changed_when: False
  tags:
    - postgresql

- name: PosgreSQLリポジトリをインストール
  yum: name="http//yum.postgresql.org/9.4/redhat/rhel-7-x86_64/pgdg-centos94-9.4-2.noarch.rpm"
  when: pgdg_status|failed
  tags:
    - postgresql

- name: PostgreSQLをインストール
  yum: name={{ item }} state=present
  with_items:
    - postgresql94-server
    - postgresql94
    - python-psycopg2
  tags:
    - postgresql

- name: PostgreSQLデータベースを初期化
  command: /usr/pgsql-9.4/bin/postgresql94-setup initdb
  args:
    creates: /var/lib/pgsql/9.4/data/postgresql.cong
  tags:
    - postgresql

- name: pg_hba.confテンプレートを転送
  template: src=files/postgresql/pg_hba.conf.j2 dest=/var/lib/pgsql/9.4/data/pg_hba.conf
  notify:
    - PostgreSQLを再起動
  tags:
    - postgresql

- name: PostgreSQLを起動、自動起動を有効化
  service: name=postgresql-9.4 state=started enabled=yes
  tags:
    - postgresql

- name: PostgreSQLユーザを作成
  postgresql_user:
    name={{ db_username }}
    password={{ db_password }}
    role_attr_flags=CREATEDB,NOSUPERUSER
    become_user: posgres
    tags:
      - postgresql

- name: アプリケーションデータベースを作成
  postgresql_db: name={{ item }} owner={{ db_username }} encoding=UTF-8 template=template0
  become_user: postgres
  with_items:
    - "{{ db_database }}"
    - "{{ db_test_database }}"
  tags:
    - postgresql
```

#### `pg_hba.conf.j2` テンプレートの可変部分
```
# TYPE DATABASE USER ADDRESS METHOD

# "local" is for Unix domain socket connections only
local all                    postgres         peer
local {{ db_database }}      {{ db_username}} md5
local {{ db_test_database }} {{db_username }} md5
```

#### PostgreSQLを再起動するハンドラ
- name: PostgreSQLを再起動
  service: name=postgresql-9.4 state=restarted
