### ISSUE TITLE
Ansibleでアプリケーションをデプロイ出来るようにする

### ISSUE THREAD

**Issue by lyuich** [lyuich/brain#53]
### Write a summary of this issue
- Ansibleでアプリケーションをデプロイ出来るようにする

### List the details of what to do as a list
- [ ] デプロイの手順をPlaybookにまとめる
- [ ] ansible-playbookコマンドで実行する

### Any references (Describe URL of documents or webpages)
- #52

**Comment by lyuich** [comment]
# Ansibleでアプリケーションをデプロイ
## 前提
- アプリケーションのコードをGitリポジトリで管理している想定

### 手順
1. アプリケーションのコードをgitモジュールで取得して、srcディレクトリに展開
2. composerモジュールでPHPライブラリの依存解決
3. フレームワークが利用する設定ファイルテンプレートを転送
4. データベーススキーマを生成するためにマイグレーションを実行
5. サンプルデータをデータベースに投入
6. アプリケーションの最適化を実行

```
- name: アプリケーションのコードをデプロイ
  git:
    repo=https://github.com/lyuich/servergroup-devops-ansible-app.git
    dest={{ deploy_laravel_root }}
    accept_hostkey=True
  tags:
    - deploy

- name: Composerで依存解決
  composer:
    command=install
    working_dir={{ deploy_laravel_root }}
    no_dev={{ not deploy_laravel_debug }}
  tags:
    - deploy

- name: .envテンプレートを転送
  template: src=files/deploy/.env.j2 dest={{ deploy_laravel_root }}/.env
  tags:
    - deploy

- name: データベースのマイグレーション
  shell: php artisan migrate --env {{ deploy_laravel_env }} --force
  args:
    chdir: "{{ deploy_laravel_root }}"
  when: deploy_laravel_debug
  tags:
    -deploy

- name: サンプルデータを登録
  shell: php artisan db:seed --env {{ deploy_laravel_env }} --force
  args:
    chdir: "{{ deploy_laravel_root }};
  when: deploy_laravel_debug
  tags:
    - deploy

- name: Laravelを最適化
  shell: php artisan optimize chdir={{ deploy_laravel_root}}
  when: not deploy_laravel_debug
  tags:
    - deploy
```

## Playbookの実行
- vagrantコマンドで仮想サーバを起動
- ansible-playbookコマンドでplaybookを実行
```
$ ansible-playbook -i hosts lapp.yml --diff

PLAY **************************************
(略)

PLAY RECAP
*******************************************

vagrant_vm1              :ok=30 changed=27
unreachable=0 failed=0
```

### deployタグのタスクのみ実行
```
$ ansible-playbook -i hosts lapp.yml -t deploy
```

**Comment by lyuich** [comment]
## AnsibleでCapistranoスタイルのデプロイ
- Ansibleは構成管理だけでなく、デプロイやオーケストレーションなど幅広く利用できる

### Capistranoスタイルのデプロイ
#### Capistrano風のディレクトリ構造

```
├── current -> /path/to/releases/20160109190613
├── releases
│   ├── 20160109190602
│   ├── 20160109190608
│   └── 20160109190613
└── shared
```

##### Currentディレクトリ
- currentディレクトリはsymlinkで、releaseディレクトリにある特定のディレクトリを指す
- 通常、最新のデプロイで設置したディレクトリを指す
- Webサーバやアプリケーションサーバの設定ではこのディレクトリを指すようにする

##### releaseディレクトリ
- releaseディレクトリにはアプリケーションコードを格納する
- デプロイごとに現在日時を名前とするディレクトリを作成し、その中にコードを格納する
- 過去のデプロイによるディレクトリを保持している
- currentのリンク先を変えることで異なるバージョンのコードを動かすことが出来る

##### sharedディレクトリ
- アプリケーションが利用するデータを格納
- セッションやキャッシュ、ログなどでデプロイが行われても同じ内容が参照できる

#### デプロイの処理の流れ
1. releases/以下に現在の日時のディレクトリを生成する
2. (1)で生成したディレクトリにコードを設置する
3. currentのシンボリックリンクが1のディレクトリを指すように変更する

### Ansistranoロールを利用したデプロイ
- Ansistrano: CapistranoスタイルのデプロイをAnsibleで実現するもの
- 2つのロールで構成されている
  - `ansistrano-deploy`: デプロイを行う
  - `ansistrano-rollback`: デプロイのロールバックを行う

#### ansistrano-deployのインストール
```
$ ansible-galaxy install carlosbuenosvinos.ansistrano-deploy -p roles
```

#### ansistrano-deployでデプロイするPlaybook
- ロールの動作を制御するために必要な変数を定義
- これらの値を変えることで様々なデプロイ方法が実現できる

```
---
- hosts: web
  vars:
    ansistrano_deploy_to: /opt/application
    ansistrano_shared_paths:
      - storage/app
      - storage/framework/cache
      - storage/framework/sessions
      - storage/framework/views
      - storage/logs
    ansistrano_allow_anonymous_stats: no
    ansistrano_keep_releases: 5
    ansistrano_deploy_via: git
    ansistrano_git_repo:
      https://github.com/lyuich/servergroup-devops-ansible-app.git
    ansistrano_after_update_code_tasks_file:
      "{{ playbook_dir }}/application/after_update_code.yml"
    ansistrano_after_symlink_tasks_file:
      "{{ playbook_dir }}/application/after_symlink.yml"
roles:
  - application_directory
  - carlosbuenosivinos.ansistrano-deploy
```

#### ansistrano-deployで指定する主な変数
- `ansistrano_deploy_to` : デプロイ先の起点となるパス
- `ansistrano_shared_paths` : sharedディレクトリ以下に設置するディレクトリリスト
- `ansistrano_allow_anonymous_stats` : Ansistranoサイトに利用状況を送信するかどうか
- `ansistrano_keep_releases` : releasesディレクトリ以下に保持する世代数。この数を超えるものは古いものから削除
- `ansistrano_deploy_via` : アプリケーションコードのデプロイ方法。copy, git, rsync, s3, s3_unarchive, unarchive
- `ansistrano_git_repo` : `ansistrano_deploy_via` がgitの場合、コードを取得するブランチ
