### ISSUE TITLE
Ansible Playbookを分割し、保守性と拡張性を高める

### ISSUE THREAD

**Issue by lyuich** [lyuich/brain#54]
### Write a summary of this issue
- Playbookを分離して、保守性と拡張性を高める

### List the details of what to do as a list
- [ ] 分割するメリットと方針をまとめる
- [ ] 具体的な分割方法について記述する

### Any references (Describe URL of documents or webpages)
- なし

**Comment by lyuich** [comment]
# Playbookの分離
## 分離するメリット
- 保守性や拡張性が上がる
- 分離しておくと見通しも良くなり、内容を把握しやすくなる
- 対象ホストごとにplayを分割すると使い勝手が良くなる

## 分離する方針
- 役割ごとにPlaybookファイルを分けてそれらを連結するPlaybookを別に作る
- ansible-playbookコマンドを実行する際は、連結したPlaybookだけを動かす

## インベントリにweb, dbのグループを追加
- インベントリにweb, dbというグループを追加する
- それぞれに仮想サーバを追加する

## Playbookをweb, db, deployの3つに分離
- web.yml: ApacheとPHPに関するタスクを記述
- db.yml: PostgreSQLに関するタスクを記述
- deploy.yml: デプロイに関するタスクを記述, hostにはwebを指定

## 全てを連結するPlaybook (all.yml) を作成
- hostsをallにして、どのホストにも共通のタスクを記述する
- includeを使ってそれぞれのPlaybookを読み込む

```
- hosts: all
  become: yes
  vars:
    base_locale: LANG=ja_JP.UTF-8
    base_timezone: Asia/Tokyo
  tasks:
    - name: ロケール設定
      command: localectl set-locale {{ base_locale }}

    - name: タイムゾーン設定
      comamnd: timedatectl set-timezone {{ base_timezone }}
    
    - name: 基本パッケージをインストール
      yum: name= {{ item }} state=present
      with_items:
        - vim
        - git
        - ntp

    - name: ntpdを起動, 自動起動の有効化
      service: name=ntpd state=started enabled=yes

- include: web.yml
- include: db.yml
- include: deploy.yml
```

## all.ymlの実行
```
$ ansible-playbook -i hosts all.yml
```

## deploy.ymlの実行
- Playbookやplayを分割しておけば、目的に応じて必要なタスクだけを実行できる

```
$ ansible-playbook -i hosts deploy.yml
```

**Comment by lyuich** [comment]
# Playbookを分割して構造化する
## 1. インベントリの分割
- ホストやグループ, 変数が同じファイルに記載すると煩雑になる
- `host_vars` ディレクトリ, `group_vars` ディレクトリを利用する

### ファイル構成
```
├── host_vars
│   └── vagrant_vm1.yml
├── group_vars
│   └── vagrant.yml
├── hosts
│
```

### ホストに対する変数を記述 
- ファイル名をホスト名としたファイルを設置する
- そうすると、対象ホストのplay実行時にファイルの内容が変数として参照できる
- `host_vars/vagrant_vm1.yml`
```
---
ansible_ssh_host 192.168.34.23
```

### グループに対する変数を記述 
- グループ名をファイル名にしたファイルを設置する
- ここで記述した変数はグループに属するホストへのplay実行時に有効になる
- `group_vars/vagrant.yml`
```
~~~
ansible_ssh_user: vagrant
ansible_ssh_private_key_file:
~/.vagrant.d/insecure_private_key
is_development: True

# for apache
apache_document_root: /vagrant/src/public
apache_server_name: servergroup-devops-ansible3.dev

# for laravel and apache
deploy_laravel_root: /vagrant/src
deploy_laravel_env: local
deploy_laravel_debug: local
deploy_laravel_app_key: xxxxxxxx #要変更

# for laravel and postgresql
db_connection: pgsql
db_host: "null"
db_database: app
db_test_database: app_test
db_username: vagrant
db_password: pass
```

### 変数を退避したインベントリ
- グループとホストだけを指定するシンプルな内容
```
[vagrant]
vagrant_vm1

[web]
vagrant_vm1

[db]
vagrant_vm1
```

## 2. ロールによるPlaybookの分割
- タスクと実行に必要なファイル, ハンドラ, 変数などをグループ化して管理する手法
- ファイル群を決められたディレクトリ構成に配置することで統一的な手順でファイルを管理

### ディレクトリ構成
```
└── roles
    ├── apache
    │   ├── defaults
    │   │   └── main.yml
    │   ├── files
    │   │   └── index.html
    │   ├── handlers
    │   │   └── main.yml
    │   ├── meta
    │   │   └── main.yml
    │   ├── tasks
    │   │   └── main.yml
    │   ├── templates
    │   │   ├── httpd.conf.j2
    │   │   └── vhosts.conf.j2
    │   └── vars
    │       └── main.yml
    ├── base
    ├── deploy
    ├── php
    └── postgresql
```

### tasksディレクトリ
- apacheロールのtasks/main.yml

```
- name: Apacheをインストール
  yum: name=httpd state=present
tags:
    - apache

- name: httpd.confテンプレートを転送
  template: src=httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf owner=root group root mode=0644
  notify:
    - Apacheを再起動
  tags:
    - apache

- name: vhosts.confテンプレートを転送
  tempalte: src=vhosts.conf.j2 dest=/etc/httpd/conf.d/vhosts.conf owner=root group=root mode=0644
  notify:
    - Apacheを再起動
  tags:
    - apache

- name: Apacheを起動、自動起動を有効化
  service: name=httpd state=started enabled=yes
  tags:
    - apache
```

#### タスクを分割してmain.ymlでinclude
```
---
- name: Apacheをインストール
  include: install.yml
  tasgs:
    - apache

- name: Apacheをセットアップ
  include: setup.yml
  tags:
    - apache
```


### handlersディレクトリ
- name: Apacheを再起動
  service: name=httpd state=restarted

### defaultsディレクトリ, varsディレクトリ
- 変数とその値をディクショナリで記述
- defaultsディレクトリは全ての変数定義の中で最も優先度が低い
- varsディレクトリで定義した変数はdefaultsディレクトリよりも優先される

#### apacheロールのdefaults/main.yml: 変数のデフォルト値を記述
```
---
is_development: on

apache_document_root: /vagrant/src/public
apache_server_name: servergroup-devops-ansible3.dev
```

### filesディレクトリ, templatesディレクトリ
#### copyモジュールでfiles/index.htmlを転送する例
```
- name: index.htmlを転送
  copy: src=index.html dest=/path/to/index.html
```

### metaディレクトリ
- 依存するロールの指定を行なう

#### apacheロールとphpロールへの依存を指定する例
- 依存するロールは `dependencies` キーの値としてロールのリストを記述する
- 変数 `apache_document_root` の値を指定して上書きする

```
---
dependencies:
  - { role: apache, apache_document_root: "{{ deploy_laravel_root }}/public" }
  - php
```

#### `allow_duplicates` をyesにする
- 複数のロールで同じ依存ロールが指定された場合、通常は一度だけ実行される
- `allow_duplicates` をyesにすると指定されるたびに実行する
```
---
allow_duplicates: yes
dependencies:
  - role1
```

### Playbookでロールを指定
#### Playbookで実行ロールを指定する例
- base, apache, phpという3つのロールを実行する
- ロールは、ロール名またはディクショナリで指定
```
---
- hosts: web
  become: yes
  roles:
    - base
    - { role: apache, apache_document_root: "{{ deploy_laravel_root }}/public" }
    - role: php
      php_extensions: [ php_mbstring, php-pgsql ]
      when: need_php
```

### lapp.ymlをロールで分離
```
├── Vagrantfile
├── group_vars
│   └── vagrant.yml
├── host_vars
│   └── vagrant_vm1.yml
├── hosts
├── lapp.yml
├── roles
│   ├── apache
│   ├── base
│   ├── deploy
│   ├── php
│   └── postgresql
└── src
```

#### タスクをロールで分割したlapp.yml
- Playbookでは `roles` で実行ロールを指定するのみ
- 対象ホストと実行ロールを指定しているのみでシンプル
- Playbookは、ロールで役割ごとに小さな単位で実装していくのがポイント
```
---
- hosts: all
  become: yes
  roles:
    - base

- hosts: db
  become: yes
  roles:
    - postgresql

- hosts: web
  become: yes
  roles:
    - apache
    - php

- hosts: web
  roles:
    - deploy
```
